### ISSUE TITLE
ライセンス表記が無い

### ISSUE THREAD

**Issue by cosmo0920** [katsyoshi/mikutter-macalsa#1]
ライセンス表記が無いリポジトリは **No License** 扱いとなる。

No Licenseのリポジトリはフォークと閲覧は[Githubのサービス利用規約](https://help.github.com/articles/github-terms-of-service/)からは許可されます。
ライセンス表記が無かったのでプルリクエストが行えない。

と言う訳で、同じようなプラグインを作ってしまいました→https://github.com/cosmo0920/mikutter-core-audio
ヽ('ω')ﾉ三ヽ('ω')ﾉもうしわけねぇもうしわけねぇ

**Comment by katsyoshi** [comment]
ok, そっちに移行しよう。

**Comment by cosmo0920** [comment]
あざっす！
